services:
  app:
    image: ${DOCKER_USERNAME}/motora:latest
    # image: thilinathushan/motora:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: motora-app
    restart: unless-stopped
    working_dir: /var/www/
    env_file: .env.docker
    # volumes:
    #   - ./:/var/www
    networks:
      - motora
    command: ["./entrypoint.sh"]

  db:
    image: mysql
    # image: mysql:8.0
    container_name: motora-db
    restart: unless-stopped
    env_file: .env.docker
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - motora
  nginx:
    image: nginx:1.27.3-alpine
    container_name: motora-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/sites-available/motora
    networks:
      - motora
    command: >
      sh -c "ln -s /etc/nginx/sites-available/motora /etc/nginx/sites-enabled/ &&
             nginx -g 'daemon off;'"

    # platform: linux/amd64

networks:
  motora:
    driver: bridge
