services:
  app:
    image: ${DOCKER_USERNAME}/motora:latest
    # image: thilinathushan/motora:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: motora-app
    restart: unless-stopped
    working_dir: /var/www/
    env_file: .env
    volumes:
      - app-code:/var/www
    networks:
      - motora
    depends_on:
      - db
    # command: ["./entrypoint.sh"]

  db:
    image: mysql
    # image: mysql:8.0
    container_name: motora-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - motora-db-data:/var/lib/mysql
    networks:
      - motora
  nginx:
    build:
      context: ./docker-compose/nginx
    container_name: motora-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - app-code:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - motora
    depends_on:
      - app
    # platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: motora-phpmyadmin
    restart: unless-stopped
    environment:
    PMA_HOST: motora-db
    PMA_PORT: 3306
    networks:
    - motora
    depends_on:
    - db

networks:
  motora:
    driver: bridge

volumes:
  app-code:
  motora-db-data:
