#!/bin/bash

# Exit immediately if a command fails
set -e

echo "🚀 EntryPoint Activated at $(date)"

# Use the existing .env.example as the template
if [ ! -f /var/www/.env.example ]; then
    echo "ERROR: .env.example file not found!"
    exit 1
fi

echo "Generating .env file from .env.example and environment variables..."

# Create a fresh .env file
> /var/www/.env

# Read the .env.example file, filter out comments and blank lines,
# and then build the final .env file.
grep -v -e '^#' -e '^\s*$' /var/www/.env.example | while IFS= read -r line; do
    # Get the variable name (everything before the '=')
    var_name=$(echo "$line" | cut -d '=' -f 1)

    # Get the value of that variable from the environment.
    # The `${!var_name}` syntax is bash for indirect expansion.
    var_value="${!var_name}"

    # Write "VAR_NAME=VAR_VALUE" to the .env file
    echo "$var_name=$var_value" >> /var/www/.env
done

echo ".env file created successfully."

# --- WAIT FOR DATABASE SECTION ---
echo "Waiting for database to be ready..."
until mysqladmin ping -h"$DB_HOST" -u"$DB_USERNAME" -p"$DB_PASSWORD" --silent; do
    echo "Database is unavailable - sleeping"
    sleep 2
done
echo "Database is ready!"
# --- END: WAIT FOR DATABASE SECTION ---

role=${1:-app}

if [ "$role" = "app" ]; then
    echo "Running APP container setup..."
    php artisan migrate --force
    php artisan key:generate --force
    php artisan storage:link

    INIT_LOCK_FILE="/var/www/storage/app/.initialized"
    if [ ! -f "$INIT_LOCK_FILE" ]; then
        echo "🌱 First-time setup: Seeding database..."
        php artisan db:seed --force
        touch "$INIT_LOCK_FILE"
        echo "✅ Seeding complete. Lock file created."
    fi

    echo "Caching configuration for production..."
    php artisan optimize

    echo "Initialization complete. Starting PHP-FPM..."
    exec php-fpm

elif [ "$role" = "worker" ]; then
    echo "Running WORKER container setup..."
    # REMOVED php artisan config:cache - It's not needed here.
    # The worker will use the cache generated by the 'app' container.

    echo "Initialization complete. Starting Supervisor..."
    exec /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf

else
    echo "Running custom command: $@"
    exec "$@"
fi