name: Motora Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub or another registry
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      # Copy compose.yaml to VM
      - name: Copy compose.yaml to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: compose.yaml
          target: /home/${{ secrets.VM_USERNAME }}/motora-app/compose.yaml

      # Debugging files on the VM
      - name: Debugging VM Files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Checking /home/${{ secrets.VM_USERNAME }}/motora-app:"
            ls -la /home/${{ secrets.VM_USERNAME }}/motora-app

      # SSH into the VM and deploy
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.VM_USERNAME }}/motora-app
            cd /home/${{ secrets.VM_USERNAME }}/motora-app
            docker pull ${{ vars.DOCKER_USERNAME }}/motora:latest
            docker compose -f compose.yaml down
            docker compose -f compose.yaml up -d
