name: Motora Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub or another registry
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      # SSH into the VM and deploy
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Step 1: Pull the latest Docker image
            docker pull ${{ vars.DOCKER_USERNAME }}/motora:latest

            # Step 2: Ensure necessary directories exist on the VM
            mkdir -p ~/motora-app

      - name: Debugging Files
        run: |
          echo "Current Directory: $(pwd)"
          echo "Files:"
          ls -la

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debugging file paths
      - name: Debug file paths
        run: |
          echo "Listing files in the workspace:"
          ls -la
          echo "Contents of compose.yaml:"
          cat compose.yaml || echo "compose.yaml not found!"
          echo "Contents of entrypoint.sh:"
          cat entrypoint.sh || echo "entrypoint.sh not found!"

      # Transfer files
      - name: Transfer compose.yaml and entrypoint.sh to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "compose.yaml, entrypoint.sh"
          target: ~/motora-app/

      # Run Docker Compose
      - name: Run Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/motora-app
            docker compose down
            docker compose up -d
