name: Motora Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ===============================================================
      #  PART 1: BUILD AND PUSH DOCKER IMAGE (This part is correct)
      # ===============================================================

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ===============================================================
      #  PART 2: DEPLOY TO VM (This is the simplified, correct part)
      # ===============================================================

      - name: Copy compose.yaml to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "compose.yaml"
          target: "~/motora-app"

      - name: Deploy and Run on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Navigate to the application directory on the VM
            cd ~/motora-app

            # Create the .env file securely from the GitHub Secret.
            # This ONE command creates the complete, correct file every time.
            echo "${{ secrets.PROD_ENV_FILE }}" > .env.docker
            echo "✅ .env.docker file created on VM."

            # Pull the latest version of the image we just pushed to Docker Hub
            docker compose pull

            # Bring down any old containers and REMOVE STALE VOLUMES
            docker compose down --volumes

            # Start the new stack in detached mode. Docker Compose will use the
            # compose.yaml and the .env.docker file we just created.
            docker compose up -d

            echo "🚀 Deployment to Azure VM successful!"
