name: Motora Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub or another registry
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          no-cache: true
          pull: true

      # SSH into the VM and deploy
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Step 1: Pull the latest Docker image
            docker pull ${{ vars.DOCKER_USERNAME }}/motora:latest

            # Step 2: Ensure necessary directories exist on the VM
            mkdir -p ~/motora-app

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate .env.docker file
        run: |
          echo "DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}" > .env.docker
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env.docker
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.docker
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.docker
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.docker
          cat .env.docker  # Optional: Print the file content for debug purposes

      # Transfer files
      - name: Transfer compose.yaml and entrypoint.sh to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "compose.yaml, entrypoint.sh, .env.docker"
          target: ~/motora-app/

      # Run Docker Compose
      - name: Run Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/motora-app

            # Export the environment variable
            export DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
            # Optional: Debug to confirm the variable is set
            echo "DOCKER_USERNAME=$DOCKER_USERNAME"

            docker compose down
            docker compose --env-file .env.docker up -d
