name: Motora Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ===============================================================
      #  PART 1: BUILD AND PUSH DOCKER IMAGE (This part is correct)
      # ===============================================================

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ===============================================================
      #  PART 2: DEPLOY TO VM (This is the simplified, correct part)
      # ===============================================================

      - name: Create deployment archive
        # We bundle everything needed for deployment into a single tarball.
        # This includes the compose file and the entire docker-compose directory.
        run: tar -czf deploy.tar.gz compose.yaml docker-compose/

      - name: Copy deployment archive to VM
        # We only need to copy this one single file.
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "deploy.tar.gz"
          target: "~/motora-app"

      - name: Deploy and Run on VM
        # This single step securely creates the environment file, unpacks the
        # archive, and restarts the application.
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Navigate to the application directory on the VM
            cd ~/motora-app

            # Unpack the archive, overwriting any old files.
            tar -xzf deploy.tar.gz
            echo "✅ Deployment archive unpacked."

            # Create the .env file securely from the GitHub Secret.
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            echo "✅ .env file created on VM."

            # Now, Docker Compose will find everything it needs:
            # compose.yaml, .env, and the docker-compose/nginx/ directory.
            
            # Pull the latest image for the app service
            docker compose pull app

            # Bring down the old stack and remove any stale volumes
            docker compose down --volumes

            # Start the new stack in detached mode.
            # It will build the custom nginx image automatically.
            docker compose up -d --build

            echo "🚀 Deployment to Azure VM successful!"
